### ISSUE TITLE
Assay Analysis Issues - NULL Exception - Spectrum ID cannot be found

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-archive-pipelines#197]
**Investigation:**

`/nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20191111_154451/log/assay_analyse_distinct/assay_analyse-PXD011501-100646-201911132100.log`

```
(base) C02W21Q1HV2R:internal hewapathirana$ grep "scan=8932" Nu-3-3.mzid
        <SpectrumIdentificationResult spectraData_ref="ID_MZML_FILE_with_spectra" spectrumID="scan=8932 file=553" id="SIR_553_8932">
(base) C02W21Q1HV2R:internal hewapathirana$ grep "scan=8932" Nu-3-3.mzML
        <spectrum index="8931" id="controllerType=0 controllerNumber=1 scan=8932" defaultArrayLength="331">
          <cvParam cvRef="MS" accession="MS:1000796" name="spectrum title" value="Nu-3-3.8932.8932.3 File:&quot;Nu-3-3.raw&quot;, NativeID:&quot;controllerType=0 controllerNumber=1 scan=8932&quot;"/>
      <offset idRef="controllerType=0 controllerNumber=1 scan=8932">75809460</offset>
```

**Error fired at**: https://github.com/PRIDE-Archive/pride-archive-pipelines/blob/4b75ff81398ba4b3046cfc3300f260878b5a06bf/src/main/java/uk/ac/ebi/pride/archive/pipeline/jobs/molecules/PRIDEAnalyzeAssayJob.java#L803-L805

**Error:**

```
E|PRIDEAnalyzeAssayJob                    |null
java.lang.NullPointerException: null
	at uk.ac.ebi.jmzml.xml.util.EscapingXMLUtilities.escapeCharacters(EscapingXMLUtilities.java:124)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.getSpectrumById(MzMLUnmarshaller.java:416)
```

**SpectrumId value**

**Actual value** : "scan=8932 file=553"
**Expected value** :  "controllerType=0 controllerNumber=1 scan=8932"

**Comment by sureshhewabi** [comment]
**Investigation:**

/nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20191111_154451/log/assay_analyse_distinct/assay_analyse-PXD008493-83080-201911140948.log

```
(base) C02W21Q1HV2R:internal hewapathirana$ grep index=33553 151029_OPDpool_1.mzid
        <SpectrumIdentificationResult spectraData_ref="SPECTRADATA_76" spectrumID="index=33553" id="SPECGROUP_3980166">
```

```
(base) C02W21Q1HV2R:internal hewapathirana$ grep "33554" 151029_OPDpool_1.mzML
        <spectrum index="33553" id="controllerType=0 controllerNumber=1 scan=33554" defaultArrayLength="411">
        ...
        <spectrum index="33554" id="controllerType=0 controllerNumber=1 scan=33555" defaultArrayLength="302">
```

Error:

```
2019-11-14 10:11:25,254 ERROR main uk.ac.ebi.pride.archive.pipeline.jobs.molecules.PRIDEAnalyzeAssayJob$2: null
java.lang.NullPointerException: null
        at uk.ac.ebi.jmzml.xml.util.EscapingXMLUtilities.escapeCharacters(EscapingXMLUtilities.java:124)
        at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.getSpectrumById(MzMLUnmarshaller.java:416)
        at uk.ac.ebi.pride.tools.mzdata_wrapper.MzMlWrapper.getSpectrumById(MzMlWrapper.java:135)
        at uk.ac.ebi.pride.archive.pipeline.services.pia.JmzReaderSpectrumService.getSpectrum(JmzReaderSpectrumService.java:82)
```

**Error fired at:**

https://github.com/PRIDE-Archive/pride-archive-pipelines/blob/4b75ff81398ba4b3046cfc3300f260878b5a06bf/src/main/java/uk/ac/ebi/pride/archive/pipeline/services/pia/JmzReaderSpectrumService.java#L79-L86

**SpectrumId value**

Actual value : "33554"
Expected value : "controllerType=0 controllerNumber=1 scan=33554"
