### ISSUE TITLE
The jobs are finishing always with exit status -1

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#31]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
00:05:14.364 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at uk.ac.ebi.pride.archive.pipeline.ArchiveSubmissionPipeline.main(ArchiveSubmissionPipeline.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException: null
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.executeLocalJobs(JobLauncherCommandLineRunner.java:174)
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.launchJobFromProperties(JobLauncherCommandLineRunner.java:134)
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.run(JobLauncherCommandLineRunner.java:128)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797)
	... 13 common frames omitted

**Comment by sureshhewabi** [comment]
@ypriverol 
your job parameter keys are incorrect. It should be:

`public Tasklet initJob(@Value(“#{jobParameters[‘projectAccession’]}“) String projectAccession, @Value(“#{jobParameters[‘assayAccession’]}“) String assayAccession){`

in `PRIDEAnalyzeAssayJob` class

**Comment by ypriverol** [comment]
Issue solve in previous my last commit. https://github.com/PRIDE-Archive/pride-archive-pipelines/commit/7c89f4df1f9b4ee1afe812fe6e1be969cbfff895
